/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 floppy.gltf --transform
Author: JackPegasus (https://sketchfab.com/JackPegasus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floppy-3b492d37ca4d43a8817087cb7861950f
Title: Floppy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/floppy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['Cube048_������������_��������������_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Cube048_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube048_Material009_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube048_Material007_0.geometry} material={materials['Material.007']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/floppy-transformed.glb')
