/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 rocket.glb --transform
Author: neatpolygons (https://sketchfab.com/neatpolygons)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/relativistic-kill-vehicle-kurzgesagt-cd4f02c868314a5fb7c786d6df8e6773
Title: Relativistic Kill Vehicle - Kurzgesagt
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/rocket-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Circle002_0" position={[0.41, 0, 0]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Material} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
              </group>
              <group name="Circle003_1" position={[0.41, 0, 0]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Material} />
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.002']} />
              </group>
              <group name="Circle004_2" position={[0.41, 0, 0]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.002']} />
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Material.008']} />
              </group>
              <group name="Circle005_3" position={[1.7, 0, 0]}>
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material} />
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['Material.002']} />
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.010']} />
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['Material.011']} />
              </group>
              <group name="Circle006_4" position={[-0.56, 0, 0]}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Material} />
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['Material.010']} />
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.011']} />
              </group>
              <group name="Circle007_5" position={[-1.24, 0, 0]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Material} />
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials['Material.002']} />
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.006']} />
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials['Material.007']} />
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.008']} />
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials['Material.010']} />
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.011']} />
              </group>
              <group name="Circle008_6">
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Material} />
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials['Material.001']} />
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Material.002']} />
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials['Material.006']} />
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Material.007']} />
                <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials['Material.008']} />
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['Material.010']} />
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials['Material.011']} />
              </group>
              <group name="Circle009_7" position={[0.44, 0, 0]}>
                <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Material} />
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
                <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials['Material.002']} />
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.005']} />
                <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials['Material.008']} />
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.011']} />
                <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials['Material.010']} />
              </group>
              <group name="Circle010_8" position={[0.98, 0, 0]}>
                <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Material} />
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.001']} />
                <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials['Material.002']} />
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.008']} />
                <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials['Material.010']} />
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['Material.011']} />
              </group>
              <group name="Plane_9" position={[0.75, -0.01, 0]} scale={[0.03, 1, 1]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials['Material.011']} />
                <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials['Material.003']} />
              </group>
              <group name="Circle011_10" position={[-0.66, 0.84, -0.02]}>
                <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials['Material.003']} />
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Material.004']} />
                <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials['Material.005']} />
              </group>
              <group name="Circle012_11" position={[-0.65, -0.49, -0.68]}>
                <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials['Material.003']} />
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Material.004']} />
                <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials['Material.005']} />
              </group>
              <group name="Circle013_12" position={[-0.64, -0.42, 0.73]}>
                <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials['Material.003']} />
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['Material.004']} />
                <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials['Material.005']} />
              </group>
              <group name="Sphere_13">
                <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere001_14">
                <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere002_15">
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere003_16">
                <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere004_17">
                <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere005_18">
                <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere006_19">
                <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere007_20">
                <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere008_21">
                <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere009_22">
                <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere010_23">
                <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere011_24">
                <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere012_25">
                <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere013_26">
                <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere014_27">
                <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere015_28">
                <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere016_29">
                <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere017_30">
                <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere018_31">
                <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere019_32">
                <mesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere020_33">
                <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere021_34">
                <mesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere022_35">
                <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere023_36">
                <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere024_37">
                <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere025_38">
                <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere026_39">
                <mesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere027_40">
                <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere028_41">
                <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere029_42">
                <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere030_43">
                <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere031_44">
                <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere032_45">
                <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere033_46">
                <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere034_47">
                <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere035_48">
                <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere036_49">
                <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere037_50">
                <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere038_51">
                <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere039_52">
                <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere040_53">
                <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere041_54">
                <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere042_55">
                <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere043_56">
                <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials['Material.009']} />
              </group>
              <group name="Sphere044_57">
                <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials['Material.009']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rocket-transformed.glb')
